version: "3.9"
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  backend:
    depends_on:
      - redis
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/time_recording?authSource=admin
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=example12345
    restart: on-failure
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    depends_on:
      - backend
    restart: on-failure
    build: ./frontend
    ports:
      - "9000:80"
